import requests
import os
import json
from .base import AIProvider
from typing import Dict, Any

class LocalAIProvider(AIProvider):
    """Local provider using Ollama (Llama 3/3.2)."""

    def __init__(self):
        self.base_url = os.getenv("LLM_BASE_URL", "http://localhost:11434/api/generate")
        self.model = os.getenv("LLM_MODEL", "llama3.2")

    def explain_prediction(self, facts: Dict[str, Any]) -> str:
        prompt = f"Explain these Jyotish facts in 2 sentences: {json.dumps(facts)}"
        try:
            resp = requests.post(self.base_url, json={
                "model": self.model,
                "prompt": prompt,
                "stream": False
            }, timeout=10.0)
            return resp.json().get("response", "Explanations are currently generated by facts only.")
        except Exception:
            return "Local AI connection failed. Showing raw facts."

    def chat_consultation(self, user_msg: str, chart_context: Dict[str, Any]) -> str:
        # Implementation for full chat
        return "Local consultation active."

    def get_status(self) -> bool:
        try:
            requests.get(os.getenv("LLM_BASE_URL", "http://localhost:11434/api/tags"), timeout=1.0)
            return True
        except: return False
